// Code generated by protoc-gen-go. DO NOT EDIT.
// source: my/my.proto

package my

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ParamValue struct {
	// Types that are valid to be assigned to ValueOneof:
	//	*ParamValue_Double
	//	*ParamValue_Int
	//	*ParamValue_Bool
	//	*ParamValue_String_
	ValueOneof           isParamValue_ValueOneof `protobuf_oneof:"value_oneof"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ParamValue) Reset()         { *m = ParamValue{} }
func (m *ParamValue) String() string { return proto.CompactTextString(m) }
func (*ParamValue) ProtoMessage()    {}
func (*ParamValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_c42ba998dd4d6253, []int{0}
}

func (m *ParamValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParamValue.Unmarshal(m, b)
}
func (m *ParamValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParamValue.Marshal(b, m, deterministic)
}
func (m *ParamValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParamValue.Merge(m, src)
}
func (m *ParamValue) XXX_Size() int {
	return xxx_messageInfo_ParamValue.Size(m)
}
func (m *ParamValue) XXX_DiscardUnknown() {
	xxx_messageInfo_ParamValue.DiscardUnknown(m)
}

var xxx_messageInfo_ParamValue proto.InternalMessageInfo

type isParamValue_ValueOneof interface {
	isParamValue_ValueOneof()
}

type ParamValue_Double struct {
	Double float64 `protobuf:"fixed64,1connectionSimple,opt,name=double,proto3,oneof"`
}

type ParamValue_Int struct {
	Int int64 `protobuf:"varint,2,opt,name=int,proto3,oneof"`
}

type ParamValue_Bool struct {
	Bool bool `protobuf:"varint,3,opt,name=bool,proto3,oneof"`
}

type ParamValue_String_ struct {
	String_ string `protobuf:"bytes,4,opt,name=string,proto3,oneof"`
}

func (*ParamValue_Double) isParamValue_ValueOneof() {}

func (*ParamValue_Int) isParamValue_ValueOneof() {}

func (*ParamValue_Bool) isParamValue_ValueOneof() {}

func (*ParamValue_String_) isParamValue_ValueOneof() {}

func (m *ParamValue) GetValueOneof() isParamValue_ValueOneof {
	if m != nil {
		return m.ValueOneof
	}
	return nil
}

func (m *ParamValue) GetDouble() float64 {
	if x, ok := m.GetValueOneof().(*ParamValue_Double); ok {
		return x.Double
	}
	return 0
}

func (m *ParamValue) GetInt() int64 {
	if x, ok := m.GetValueOneof().(*ParamValue_Int); ok {
		return x.Int
	}
	return 0
}

func (m *ParamValue) GetBool() bool {
	if x, ok := m.GetValueOneof().(*ParamValue_Bool); ok {
		return x.Bool
	}
	return false
}

func (m *ParamValue) GetString_() string {
	if x, ok := m.GetValueOneof().(*ParamValue_String_); ok {
		return x.String_
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ParamValue) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ParamValue_Double)(nil),
		(*ParamValue_Int)(nil),
		(*ParamValue_Bool)(nil),
		(*ParamValue_String_)(nil),
	}
}

type SellerParams struct {
	Result               []*SellerParams_Item `protobuf:"bytes,3,rep,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SellerParams) Reset()         { *m = SellerParams{} }
func (m *SellerParams) String() string { return proto.CompactTextString(m) }
func (*SellerParams) ProtoMessage()    {}
func (*SellerParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_c42ba998dd4d6253, []int{1}
}

func (m *SellerParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SellerParams.Unmarshal(m, b)
}
func (m *SellerParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SellerParams.Marshal(b, m, deterministic)
}
func (m *SellerParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SellerParams.Merge(m, src)
}
func (m *SellerParams) XXX_Size() int {
	return xxx_messageInfo_SellerParams.Size(m)
}
func (m *SellerParams) XXX_DiscardUnknown() {
	xxx_messageInfo_SellerParams.DiscardUnknown(m)
}

var xxx_messageInfo_SellerParams proto.InternalMessageInfo

func (m *SellerParams) GetResult() []*SellerParams_Item {
	if m != nil {
		return m.Result
	}
	return nil
}

type SellerParams_Item struct {
	SellerId             int64                  `protobuf:"varint,1connectionSimple,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	Rating               float64                `protobuf:"fixed64,2,opt,name=rating,proto3" json:"rating,omitempty"`
	Params               map[string]*ParamValue `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1connectionSimple,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *SellerParams_Item) Reset()         { *m = SellerParams_Item{} }
func (m *SellerParams_Item) String() string { return proto.CompactTextString(m) }
func (*SellerParams_Item) ProtoMessage()    {}
func (*SellerParams_Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_c42ba998dd4d6253, []int{1, 0}
}

func (m *SellerParams_Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SellerParams_Item.Unmarshal(m, b)
}
func (m *SellerParams_Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SellerParams_Item.Marshal(b, m, deterministic)
}
func (m *SellerParams_Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SellerParams_Item.Merge(m, src)
}
func (m *SellerParams_Item) XXX_Size() int {
	return xxx_messageInfo_SellerParams_Item.Size(m)
}
func (m *SellerParams_Item) XXX_DiscardUnknown() {
	xxx_messageInfo_SellerParams_Item.DiscardUnknown(m)
}

var xxx_messageInfo_SellerParams_Item proto.InternalMessageInfo

func (m *SellerParams_Item) GetSellerId() int64 {
	if m != nil {
		return m.SellerId
	}
	return 0
}

func (m *SellerParams_Item) GetRating() float64 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *SellerParams_Item) GetParams() map[string]*ParamValue {
	if m != nil {
		return m.Params
	}
	return nil
}

func init() {
	proto.RegisterType((*ParamValue)(nil), "ParamValue")
	proto.RegisterType((*SellerParams)(nil), "SellerParams")
	proto.RegisterType((*SellerParams_Item)(nil), "SellerParams.Item")
	proto.RegisterMapType((map[string]*ParamValue)(nil), "SellerParams.Item.ParamsEntry")
}

func init() {
	proto.RegisterFile("my/my.proto", fileDescriptor_c42ba998dd4d6253)
}

var fileDescriptor_c42ba998dd4d6253 = []byte{
	// 277 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x50, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x6d, 0x36, 0xb5, 0x6c, 0x27, 0x0a, 0x32, 0x88, 0x84, 0x15, 0xa4, 0xee, 0xa9, 0x78, 0xa8,
	0xb0, 0x82, 0x88, 0x47, 0x41, 0xe9, 0xde, 0x24, 0x82, 0xd7, 0xa5, 0xa5, 0x51, 0x8a, 0x69, 0xb3,
	0xa4, 0xa9, 0xd0, 0x6f, 0xf3, 0xc7, 0x3c, 0x4a, 0xd2, 0x80, 0x0b, 0xde, 0xe6, 0xbd, 0x79, 0xbc,
	0xf7, 0x66, 0x80, 0x75, 0xd3, 0x4d, 0x37, 0x15, 0x7b, 0xa3, 0xad, 0x5e, 0x4f, 0x00, 0x2f, 0x95,
	0xa9, 0xba, 0xb7, 0x4a, 0x8d, 0x12, 0x39, 0x24, 0x8d, 0x1e, 0x6b, 0x25, 0x39, 0xc9, 0x48, 0x4e,
	0xca, 0x48, 0x04, 0x8c, 0x08, 0xb4, 0xed, 0x2d, 0x5f, 0x64, 0x24, 0xa7, 0x65, 0x24, 0x1c, 0xc0,
	0x33, 0x88, 0x6b, 0xad, 0x15, 0xa7, 0x19, 0xc9, 0x97, 0x65, 0x24, 0x3c, 0x72, 0x1e, 0x83, 0x35,
	0x6d, 0xff, 0xc1, 0xe3, 0x8c, 0xe4, 0xa9, 0xf3, 0x98, 0xf1, 0xe3, 0x09, 0xb0, 0x2f, 0x17, 0xb3,
	0xd3, 0xbd, 0xd4, 0xef, 0xeb, 0x1f, 0x02, 0xc7, 0xaf, 0x52, 0x29, 0x69, 0x7c, 0x83, 0x01, 0xaf,
	0x21, 0x31, 0x72, 0x18, 0x95, 0xe5, 0x34, 0xa3, 0x39, 0xdb, 0x60, 0x71, 0xb8, 0x2e, 0xb6, 0x56,
	0x76, 0x22, 0x28, 0x56, 0xdf, 0x04, 0x62, 0x47, 0xe0, 0x05, 0xa4, 0x83, 0x57, 0xed, 0xda, 0xc6,
	0xb7, 0xa6, 0x62, 0x39, 0x13, 0xdb, 0x06, 0xcf, 0x21, 0x31, 0x95, 0x75, 0x5d, 0x5c, 0x71, 0x22,
	0x02, 0xc2, 0x3b, 0x48, 0xf6, 0xde, 0x34, 0x24, 0x5d, 0xfe, 0x4f, 0x2a, 0xe6, 0xf9, 0xa9, 0xb7,
	0x66, 0x12, 0x41, 0xbd, 0x7a, 0x06, 0x76, 0x40, 0xe3, 0x29, 0xd0, 0x4f, 0x39, 0xf9, 0xd4, 0x54,
	0xb8, 0x11, 0xaf, 0xe0, 0xc8, 0x9f, 0xe8, 0xf3, 0xd8, 0x86, 0x15, 0x7f, 0xcf, 0x15, 0xf3, 0xe6,
	0x61, 0x71, 0x4f, 0xea, 0xc4, 0x3f, 0xff, 0xf6, 0x37, 0x00, 0x00, 0xff, 0xff, 0x37, 0x4f, 0xda,
	0x30, 0x8b, 0x01, 0x00, 0x00,
}
