version: "3.3"

services:
  category-service:
    build: ./category-service
    ports:
      - 6000:6000
      - 6001:6001
      - 6002:6002
  product-service:
    build: ./product-service
    ports:
      - 7000:7000
      - 7001:7001
      - 7002:7002
  postgres-ps:
      image: postgres:12-alpine
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports:
        - '5432:9432'
      volumes:
        - ./postgres-data:/var/lib/postgresql/data